---
# Ansible playbook to import F5 BIG-IQ device inventory to Ansible INI inventory
#  - Improved version called bigiq_import_inventory_v3.yml
#     > uses token auth and inserts into existing inventory file

# fetches bigiq device list via api, 
# creates ansible ini inventory file with some header info
# and adds bigiq devices

# header information includes date/time and source hostname/IP

- hosts: "{{host}}"
  connection: local
  vars:
    dest_file: "../test_bigiq_inv.ini"
  gather_facts: yes
  tasks:

  - name: Calling API to get BIG-IQ device list for Ansible inventory
    uri:
      url: https://{{ ansible_host }}/mgmt/shared/resolver/device-groups/cm-bigip-allDevices/devices?$select=hostname,managementAddress,uuid
      user: "{{ username }}"
      password: "{{ latest_passwd }}"
      force_basic_auth: yes
      method: GET
      return_content: yes
      status_code: 200
      validate_certs: no
      headers:
        Content-Type: "application/json"
        body_format: json
    register: json_response

  - name: Check and delete inventory file if there
    file:
      path: "{{ dest_file }}"
      state: absent

  - name: Create file and add inventory header information
    lineinfile:
      dest: "{{ dest_file }}"
      line: "{{ item }}"
      create: yes
    loop:
      - "\n"
      - "[bigiq_devices]"
      - "# Ansible inventory imported from {{ inventory_hostname }} @ {{ ansible_host }}"
      - "# Imported on {{ ansible_date_time.iso8601 }}"

  - name: Add bigiq managed bigip devices to file
    lineinfile:
      dest: "{{ dest_file }}"
      line: "{{ item.hostname }}   ansible_host={{ item.managementAddress }}   uuid={{ item.uuid }}"
    with_items: "{{ json_response['json']['items'] }}"

