---
#  Playbook to complete necessary items in the f5 initial config wizard
#    Update root/admin password, give admin advanced shell access (bash), 
#    set ntp/dns, regen device certificate and admin routes

# todo: set admin routes, check current device cert, push rsa pub key

# admin routes aren't part of the initial configuration wizard, but they \
#  are needed to get everything working for bigiq import mainly time sync

- hosts: localhost
  connection: local
  gather_facts: no
  environment:
    F5_VALIDATE_CERTS: false
  vars:
    ansible_host: "{{ new_host }}"
  vars_prompt:
    - name: "new_host"
      prompt: "hostname(inv-fqdn): "
      private: no

#  vars:
#    provider:
#      user: "{{ username }}"
#      password: "{{ latest_passwd }}"
#      server: "{{ ansible_host }}"
  
  tasks:
  
#  - name: Initial config wizard plays
#    block:


  - include_tasks: set_admin_pass_from_default.yml
  - include_tasks: set_admin_advance_shell.yml
  
  - include_tasks: add_rsa_pub_id.yml
    when: rsa_pub_id is defined

  - name: Get device hostname
    uri:
      url: "https://{{ ansible_host }}/mgmt/tm/util/bash"
      method: POST
      body: 
        command: run
        utilCmdArgs: "-c 'echo $HOSTNAME'"
      body_format: json
      validate_certs: no
      force_basic_auth: yes
      user: "{{ username }}"
      password: "{{ latest_passwd }}"
      headers:
        Content-Type: "application/json"
    register: hostname_result  
    # todo: research ansible fact = f5 hostname
  
  - name: Extract hostname form hostname_result
    set_fact: 
      #hostname: "{{hostname_result.json.commandResult.split(\".\")[0]}}"
      hostname: "{{hostname_result.json.commandResult  | replace('\n', '')}}"

  - name: Update root password
    include_tasks: set_root_pass.yml

  - name: Disable gui setup wizard
    include_tasks: gui_setup_disable.yml

  - name: Regenerate Device Certificate
    include_tasks: regen_device_cert.yml
      # uses hostname var
   
  - name:  set admin routes
    include_tasks: set_admin_routes.yml
    when: admin_routes is defined

  - name: Set GUI banner information
    include_tasks: set_gui_advisory_banner.yml
    when: gui_advisory is defined

  - name: Set SNMP details
    include_tasks: set_snmp.yml

  - name: Set syslog destination using custom play
    include_tasks: "../{{syslog_play}}"
    when: syslog_play is defined
    # this var points to a customer specific syslog play
    # that sets syslog destination depending on datacenter

  - name: Set syslog normally
    include_tasks: set_syslog.yml
    when: syslog is defined and syslog_play is not defined

  - name: Set RADIUS admin auth
    include_tasks: set_radius_sys_auth.yml

  - name: Set default node monitor
    include_tasks: set_default_node_monitor.yml

  - name: Set gui login banner
    include_tasks: set_gui_login_banner.yml

  - name: Set ssh login banner
    include_tasks: set_ssh_login_banner.yml

  - name:  Set ssh timeout
    include_tasks: set_ssh_timeout.yml

  - name:  Set DNS
    include_tasks: set_dns.yml
    when: dnsl is defined

  - name: Set NTP
    include_tasks: set_ntp.yml
    when: ntpl is defined

  - name:  No Update, no phone home
    include: no_update_no_phone_home.yml

  - name: Set preferences
    include: set_preferences.yml

  - name: Create users
    include_tasks: create_users.yml
    when: users is defined  

  - name: Save config
    include_tasks: ../save_sys_config.yml














