---


- name: Set local DNS settings
  bigip_device_dns:
    user: "{{ username }}"
    password: "{{ latest_passwd }}"
    server: "{{ ansible_host }}"
    name_servers: "{{ dnsl }}"
    validate_certs: no
  #with_items: "{{ "

