---
# Ansible playbook to import F5 BIG-IQ device inventory to Ansible INI inventory

# fetches bigiq auth token, calls device list via api, 
# Adds bigiq devices with hostname,mgmt-ip, uuid and some header info
# to end of current inventory defined to run play
#   Ben Gordon (b.gordon@f5.com)

# header information includes date/time and source hostname/IP

- hosts: "bigiq01"
  connection: local
  gather_facts: no
  vars:
    bigips: bigip31.f5.com
      #- bigip31.f5.com
      #- bigip32.f5.com
    prefix: "pre-upgrade_"  # ucs prefix
    life: 1   # number of days bigiq will keep the ucs
    desc: "some description"
  tasks:

  - name: get bigiq auth token
    uri:
      url: "https://{{ ansible_host }}/mgmt/shared/authn/login"
      method: POST
      body_format: json
      return_content: true
      validate_certs: false
      body: 
        username: "{{username}}"
        password: "{{latest_passwd}}"
        logonProviderName: "{{provider}}" 
      status_code: 200
    register: token
  
  - name: Calling bigiq API to list ucs
    uri:
      url: https://{{ ansible_host }}/mgmt/cm/system/backup-restore?$select=archiveFileName,name
      method: GET
      return_content: yes
      status_code: 200
      validate_certs: no
      headers:
        X-F5-Auth-Token: "{{token.json.token.token}}"
        Content-Type: "application/json"
      #body_format: json
      #body:
      #  devicesReference: 
      #    link: https://localhost/mgmt/shared/resolver/device-groups/cm-bigip-allBigIpDevices/devices?filter=hostname+eq+'{{ bigips }}'
      #  taskRefence:
      #    link: https://localhost/mgmt/cm/system/backup-restore
      #  taskBody:
      #    namePrefix: "{{ prefix }}"
      #    includePrivateKeys: true
      #    isEncrypted: false
      #    backupLifeTime: 1
      #    shouldCreateArchive: false
      #    passphrase: null
      #    obfuscatedPassphrase: null
      #    backupCounter: null
      #    name: "somename.ucs"
      #    description: ""
    register: json_response
    #with_items: "{{ bigips }}"



#POST  https://{{bigiq}}/mgmt/shared/group-task
#
#{
#    "devicesReference": {
#        "link": "https://localhost/mgmt/shared/resolver/device-groups/cm-bigip-allBigIpDevices/devices?#$filter=hostname+eq+'bigip31.f5.com'"
#    },
#    "taskReference": {
#        "link": "https://localhost/mgmt/cm/system/backup-restore"
#    },
#    "taskBody": {
#        "namePrefix": "uiway2_",
#        "includePrivateKeys": true,
#        "isEncrypted": false,
#        "backupLifeTime": 1,
#        "shouldCreateArchive": false,
#        "passphrase": null,
#        "obfuscatedPassphrase": null,
#        "backupCounter": null,
#        "name": "realname.ucs",
#        "description": "bigiq done did it"
#    }
#}