---

- name: Set NTP servers/timezone
  bigip_device_ntp:
    user: "{{ username }}"
    password: "{{ latest_passwd }}"
    server: "{{ ansible_host }}"
    ntp_servers: "{{ ntpl }}"
    timezone: "{{ ntp.timezone }}"
    validate_certs: no
  delegate_to: localhost
  #when: ntpl is defined
