---

- name: Check admin account details
  uri:
    url: "https://{{ ansible_host }}/mgmt/shared/authz/users/admin"
    method: GET
    body_format: json
    validate_certs: no
    force_basic_auth: yes
    user: "{{ username }}"
    password: "{{ latest_passwd }}"
    headers:
      Content-Type: "application/json"
  register: admin_account
  delegate_to: localhost

- name: Give admin advanced shell access
  uri:
    url: "https://{{ ansible_host }}/mgmt/shared/authz/users/admin"
    method: PATCH
    body: '{"shell":"bash"}'
    body_format: json
    validate_certs: no
    force_basic_auth: yes
    user: "{{ username }}"
    password: "{{ latest_passwd }}"
    headers:
      Content-Type: "application/json"
  delegate_to: localhost
  when: '"bash" not in admin_account.json.shell'