---


- name: Get an API token
  uri:
    url: "https://{{ ansible_host }}/mgmt/shared/authn/login"
    method: POST
    body:
      {
        "username": "{{ bigip_username }}",
        "password": "{{ bigip_password }}",
          "loginProviderName": "tmos"
      }
    status_code: 200
    body_format: json
    #validate_certs: "{{ validate_certs }}"
  register: auth