---

#  take list of old root/admin passwords
#  prompt for 3/4ID and password
#  try to update admin password with 3/4
# - then try default
# - then work through old passwords list
#  when successful login, update root/admin passwords

- hosts: "{{ host }}"
  connection: local
  vars_prompt:
    - name: "id_34"
      prompt: "Enter your 3/4ID:  "
      private: no
      default: "ian7423"
    - name: "id_34_pass"
      prompt: "Enter {{ id_34 }}'s password:  "
      default: "{{ id_34_pass }}"
    
  tasks:

  - name: Changing admin password with 3/4 "{{ id_34 }}"
    bigip_user:
      state: present
      username_credential: admin
      password_credential: "{{ latest_passwd }}"
      provider:
        server: "{{ host }}"
        user: "{{ id_34 }}"
        password: "{{ id_34_pass }}"
    #delegate_to: localhost
      validate_certs: no


  - name: Changing root password with 3/4 "{{ id_34 }}"
    bigip_user:
      username_credential: root
      password_credential: "{{ latest_passwd }}"
      provider:
        server: "{{ host }}"
        user: "{{ id_34 }}"
        password: "{{ id_34_pass }}"
    #delegate_to: localhost
      validate_certs: no